### ISSUE TITLE
Beyond Textual Stylization

### ISSUE THREAD

**Issue by KeitoTakaishi** [threedle/text2mesh#12]
Hi, thnak you nice work!

Can I stylize a source mesh using 2D Images or meshes in your code?

**Comment by ojmichel** [comment]
The source mesh must be a triangular mesh stored in an obj file. A 2D planar triangular mesh would work technically, but 3D objects will have the best results (we give an example in the paper of doing this). Images will not work.

**Comment by ojmichel** [comment]
Sorry I think I misunderstood your question. If you are asking about whether the target can be an image/mesh (instead of just a text prompt), currently this should be possible for images (see --image argument). You can also experiment with text + image combinations. In the paper we also show some examples of using a mesh target, but this is not yet included in the code. The way this is done is by comparing rendered views of the source and target meshes.

**Comment by KeitoTakaishi** [comment]
thank you!
I'm clear.
