### ISSUE TITLE
Help! Any suggestions?

### ISSUE THREAD

**Issue by Augustus95** [threedle/text2mesh#3]
**It may be possible to train a network to stylize a collection of meshes towards a target style in a feed-forward manner.**
![iter_7100](https://user-images.githubusercontent.com/34907785/146875173-bfd69c0a-53af-4888-abf8-c3eb79e87449.jpg)

**Comment by roibaron** [comment]
Hey @Augustus95. I'm not sure what exactly the issue is about, since the attached image doesn't make sense in the context of your sentence.
If you are trying to optimize the face mesh into some text target and facing this multi-face issue, I would recommend that you'll align your mesh. Make sure that the frontview is set to be infront of the face of the content mesh. This can be done by either by adjusting the argument frontview_center or by rotating your source mesh.
